---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: javawebdeployment 
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector: 
    matchLabels: 
      app: javawebdeployment 
  template:
    metadata:
      labels:
        app: javawebdeployment
    spec:  
      containers:
      - name: javawebapp  
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebsvc 
spec:
  type: NodePort
  selectors:
    app: javawebdeployment 
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785

...