---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    images: ashokit/javawebapp
    ports:
      - containerPort: 8080
...