---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels: 
    app: webapp
spec: 
  containers:
    - name: webapp
      image: ashokit/javawebapp
      ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: javawebappsvc
spec:
  type: NodePort
  selector: 
    app: webapp
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 30125
...
    

